"""Public contracts for reusable backgammon position analysis."""

from .cache import CacheLookup, FileCache, MemoryCache, cache_key
from .capabilities import capability_report
from .models import (
    ANALYSIS_SETTINGS,
    RESULT_SCHEMA_VERSION,
    AnalysisRequest,
    AnalysisResult,
    CheckerCandidate,
    CheckerDecision,
    ConfigurationTrace,
    CubeAction,
    CubeDecision,
    EngineConfiguration,
    EngineFailure,
    MoveFilter,
    NormalizedPosition,
    OutcomeProbabilities,
    Position,
    RawSource,
)
from .serialization import canonical_json

from .position_contract import (
    BackgammonView,
    PositionSource,
    RendererPosition,
    RendererPositionError,
    UniversalPosition,
    canonical_to_bgsage,
    create_renderer_position,
    decode_gnuid,
    decode_xgid,
    default_backgammon_view,
    enrich_position,
    renderer_position_from_gnuid,
    renderer_position_from_xgid,
    renderer_position_json,
    NativeConversionResult,
    NativeIdentifierCodecError,
    NormalizationChange,
    convert_gnuid_to_xgid,
    convert_xgid_to_gnuid,
    gnuid_from_position,
    gnuid_to_xgid,
    match_id_from_position,
    position_from_gnuid,
    position_from_xgid,
    position_id_from_position,
    xgid_from_position,
    xgid_to_gnuid,
    semantic_state_hash,
    source_record_hash,
    verify_gnu_source_bridge,
    view_hash,
)

__all__ = [
    "NativeConversionResult",
    "NativeIdentifierCodecError",
    "NormalizationChange",
    "convert_gnuid_to_xgid",
    "convert_xgid_to_gnuid",
    "gnuid_from_position",
    "gnuid_to_xgid",
    "match_id_from_position",
    "position_from_gnuid",
    "position_from_xgid",
    "position_id_from_position",
    "xgid_from_position",
    "xgid_to_gnuid",
    "ANALYSIS_SETTINGS",
    "BackgammonView",
    "PositionSource",
    "RendererPosition",
    "RendererPositionError",
    "UniversalPosition",
    "canonical_to_bgsage",
    "create_renderer_position",
    "decode_gnuid",
    "decode_xgid",
    "default_backgammon_view",
    "enrich_position",
    "renderer_position_from_gnuid",
    "renderer_position_from_xgid",
    "renderer_position_json",
    "semantic_state_hash",
    "source_record_hash",
    "verify_gnu_source_bridge",
    "view_hash",
    "RESULT_SCHEMA_VERSION",
    "AnalysisRequest",
    "AnalysisResult",
    "CacheLookup",
    "CheckerCandidate",
    "CheckerDecision",
    "ConfigurationTrace",
    "CubeAction",
    "CubeDecision",
    "EngineConfiguration",
    "EngineFailure",
    "FileCache",
    "MemoryCache",
    "MoveFilter",
    "NormalizedPosition",
    "OutcomeProbabilities",
    "Position",
    "RawSource",
    "cache_key",
    "canonical_json",
    "capability_report",
]

__version__ = "0.3.0"
