"""Universal Position v1 contracts, decoders, validation, and adapter seams."""

from .bgsage import BGSageConversionError, BGSagePosition, canonical_to_bgsage
from .decoders import decode_gnuid, decode_xgid
from .enrichment import EnrichmentError, enrich_position
from .gnu_bridge import GnuSourceBridgeError, verify_gnu_source_bridge, with_source_hash
from .hashing import (
    semantic_state_hash,
    semantic_state_json,
    source_record_hash,
    source_record_json,
    view_hash,
    view_json,
)
from .models import (
    BackgammonView,
    Board,
    CheckerCount,
    ConversionLoss,
    CubeState,
    DecodedPosition,
    FieldOrigin,
    FrozenDict,
    MatchScore,
    ParserIdentity,
    PendingAction,
    PlayerBoard,
    PositionSource,
    PositionState,
    RawSource,
    RuleState,
    UniversalPosition,
)
from .semantics import ILLEGAL, LEGAL, UNKNOWN, derive_state, doubling_legality
from .validation import (
    ContractValidationError,
    validate_backgammon_view,
    validate_contract,
    validate_origin_coverage,
    validate_position_source,
    validate_universal_position,
)

__all__ = [
    "BGSageConversionError",
    "BGSagePosition",
    "BackgammonView",
    "Board",
    "CheckerCount",
    "ContractValidationError",
    "ConversionLoss",
    "CubeState",
    "DecodedPosition",
    "EnrichmentError",
    "FieldOrigin",
    "FrozenDict",
    "GnuSourceBridgeError",
    "ILLEGAL",
    "LEGAL",
    "MatchScore",
    "ParserIdentity",
    "PendingAction",
    "PlayerBoard",
    "PositionSource",
    "PositionState",
    "RawSource",
    "RuleState",
    "UNKNOWN",
    "UniversalPosition",
    "canonical_to_bgsage",
    "decode_gnuid",
    "decode_xgid",
    "derive_state",
    "doubling_legality",
    "enrich_position",
    "semantic_state_hash",
    "semantic_state_json",
    "source_record_hash",
    "source_record_json",
    "validate_backgammon_view",
    "validate_contract",
    "validate_origin_coverage",
    "validate_position_source",
    "validate_universal_position",
    "verify_gnu_source_bridge",
    "view_hash",
    "view_json",
    "with_source_hash",
]
